pipeline{
    agent any
    stages{
        stage("checkout"){
            steps{
                checkout scm
            }
        }

        stage("SonarQube Analysis") {
          steps{
              script {
                  scannerHome = tool 'SonarScanner'
              }
              withSonarQubeEnv('mysonar') {
                  sh "${scannerHome}/bin/sonar-scanner -D sonar.nodejs.executable=/root/.nvm/versions/node/v20.14.0/bin/node"
              }
          }
        }
        stage("image build"){
            steps{
                script{
                    myapp = docker.build("myregistry.com/root/hello/hello")
                }
            }
        }
        stage("push image"){
            steps{
                script{
                    docker.withRegistry('https://myregistry.com','registry-auth'){
                        myapp.push("latest")
                    }
                }
            }
        }
/*        stage("deploy"){
            steps{
                sh "kubectl apply -f deploy-app.yml"
            }
        }
*/    }
}
