pipeline {
  agent none
  stages {
    stage('Build & Code Test') {
      agent {
        node {
          label 'docker'
        }
      }
      steps {
        sh 'mvn -Dmaven.test.failure.ignore clean package'
        stash(name: 'build-test-artifacts', \
        includes: '**/target/surefire-reports/TEST-*.xml,target/*.jar')
      }
    }
    stage('Report & Publish') {
      agent {
        node {
          label 'built-in'
        }
      }
      steps {
        unstash 'build-test-artifacts'
        junit '**/target/surefire-reports/TEST-*.xml'
        archiveArtifacts(onlyIfSuccessful: true, artifacts: 'target/*.jar')
      }
    }
    stage('Publish to Repository') {
      parallel {
        stage('Publish to Artifactory') {
          agent {
            node {
              label 'docker'
            }
          }
          steps {
            script {
              unstash 'build-test-artifacts'

              def server = Artifactory.server 'Artifactory'
              def uploadSpec = """{
                "files": [
                  {
                    "pattern": "target/*.jar",
                    "target": "example-repo-local/${BRANCH_NAME}/${BUILD_NUMBER}/"
                  }
                ]
              }"""
              server.upload(uploadSpec)
            }
          }
        }
        stage('Publish to Registry'){
          steps{
            script{
              docker.withRegistry('https://myregistry.com:8443','registry-auth'){
                myapp = docker.build("myregistry.com:8443/test/hello:${env.BUILD_ID}")
                myapp.push()
              }
            }
          }
        }
      }
    }
  }
}
