pipeline{
    agent any
    tools {
      dockerTool 'docker'
    }
    stages{
        stage("checkout"){
            steps{
                checkout scm
            }
        }

        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                dependencyCheck additionalArguments: ''' 
                    -o './'
                    -s './'
                    -f 'ALL' 
                    --prettyPrint''', odcInstallation: 'owasp'
        
    		dependencyCheckPublisher pattern: 'dependency-check-report.xml'
      	    }
    	}
    }
}
